#!/usr/bin/env bash

#Install python & friends
#sudo apt-get install -y python3.6 python3.6-dev python-dev
sudo apt-get install -y python-pip python3-pip

#ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update
sudo apt-get install -y ansible jq vim lsof nodejs npm git facter
