#!/usr/bin/env bash

#Install languages
sudo apt-get install -y python-pip python3-pip

#ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update
sudo apt-get install -y ansible jq vim lsof nodejs npm git facter
